# 端口
server:
  port: 8081
spring:
  # 当前应用的名称
  application:
    name: consumer-server
# 配置Eureka注册中心地址，
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
# 修改服务地址轮询策略，默认是轮询，配置之后变随机
consumer-demo:
  ribbon:
    #负载均衡策略的ClassName的名称    随机策略  默认为策略是轮询
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #链接超时时间, 连的过程
    ConnecTimeout: 5000
    #数据读取超时,连上之后,数据传输过程
    ReadTimeout: 2000
    #最大自动重试次数(搭建的集群中使用)
    MaxAutoRetries: 0
    #最大自动重试下一次服务
    MaxAutoRetriexNextServer: 0
    # 是否对所有的请求都重试
    OkToRetryOnAllOperations: false


#熔断器的配置
hystrix:
  command:
    default:
      circuitBreaker:
        # 强制打开熔断器 默认false关闭的。测试配置是否生效
        # forceOpen: false
        # 触发熔断错误比例阈值，默认值50%
        errorThresholdPercentage: 50
        # 熔断后休眠时长，默认值5秒
        sleepWindowInMilliseconds: 10000
        # 熔断触发最小请求次数，默认值是20
        requestVolumeThreshold: 5

      execution:
        isolation:
          thread:
            # 熔断超时设置，默认为1秒
            timeoutInMilliseconds: 2000


#开启feign熔断器支持
feign:
  hystrix:
    enabled: true
    #开启压缩
    compression:
      request:
        enabled: true
        # 最小触发压缩的大小
        min-request-size: 2048
        #触发压缩数据类型(不能使用 "", '')
        mime-types: text/xml,application/xml/application/json
        #响应压缩
      response:
        enableed: true
#配置日志的级别
logging:
  level:
    com.itheima: debug
